version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
  client:
    build:
      dockerfile: Dockerfile
      context: ./cmemnpt
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'